spring:
  application:
    name: gogo
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
