spring:
  application:
    name: gogo
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  prefix: api/v1

gogo-travel:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080