INSERT INTO amenity (id, name, icon, is_featured) VALUES
                                                      ('1', 'Free WiFi', 'IC_WIFI', true),
                                                      ('2', '24/7 Access', 'IC_CLOCK', true),
                                                      ('3', 'In-flight Entertainment', 'IC_PLANE', false),
                                                      ('4', 'Gourmet Meals', 'IC_FOOD', true),
                                                      ('5', 'Basic WiFi', 'IC_WIFI', false),
                                                      ('6', 'Airport Shuttle', 'IC_PLANE', true),
                                                      ('7', 'Breakfast Included', 'IC_FOOD', true),
                                                      ('8', 'Late Check-out', 'IC_CLOCK', false),
                                                      ('9', 'Unlimited WiFi', 'IC_WIFI', true),
                                                      ('10', 'Fast Check-in', 'IC_CLOCK', true),
                                                      ('11', 'Business Class Seats', 'IC_PLANE', true),
                                                      ('12', 'Complimentary Snacks', 'IC_FOOD', false),
                                                      ('13', 'High-Speed WiFi', 'IC_WIFI', true),
                                                      ('14', 'Flight Monitoring', 'IC_CLOCK', true),
                                                      ('15', 'Premium Meals', 'IC_FOOD', true),
                                                      ('16', 'WiFi Hotspot', 'IC_WIFI', false),
                                                      ('17', 'On-Time Service', 'IC_CLOCK', false),
                                                      ('18', 'Luxury Dining', 'IC_FOOD', true),
                                                      ('19', 'Scenic Flights', 'IC_PLANE', false),
                                                      ('20', 'WiFi Lounge', 'IC_WIFI', true);