insert into public.location (id, city, country, description)
values  ('1', 'Hà Nội', 'Việt Nam', 'Thủ đô của Việt Nam, nổi tiếng với văn hóa và ẩm thực truyền thống.'),
        ('2', 'Hồ Chí Minh', 'Việt Nam', 'Thành phố lớn nhất Việt Nam với nền kinh tế năng động.'),
        ('3', 'Đà Nẵng', 'Việt Nam', 'Thành phố biển đẹp với bãi biển Mỹ Khê nổi tiếng.'),
        ('4', 'Nha Trang', 'Việt Nam', 'Địa điểm du lịch biển hàng đầu với nhiều khu nghỉ dưỡng.'),
        ('5', 'Huế', 'Việt Nam', 'Cố đô của Việt Nam với các di tích lịch sử nổi tiếng.'),
        ('6', 'Hội An', 'Việt Nam', 'Thị trấn cổ nổi tiếng với phố cổ và đèn lồng.'),
        ('7', 'Phú Quốc', 'Việt Nam', 'Hòn đảo nổi tiếng với bãi biển đẹp và nước mắm Phú Quốc.'),
        ('8', 'Sapa', 'Việt Nam', 'Thị trấn vùng núi với cảnh quan thiên nhiên tuyệt đẹp.'),
        ('9', 'Cần Thơ', 'Việt Nam', 'Thành phố miền Tây nổi tiếng với chợ nổi và kênh rạch.'),
        ('10', 'Hải Phòng', 'Việt Nam', 'Thành phố cảng quan trọng của Việt Nam.'),
        ('11', 'Tokyo', 'Nhật Bản', 'Thủ đô hiện đại của Nhật Bản, nổi tiếng với văn hóa và công nghệ.'),
        ('12', 'Paris', 'Pháp', 'Thủ đô của Pháp, nổi tiếng với tháp Eiffel và nghệ thuật.'),
        ('13', 'New York', 'Hoa Kỳ', 'Thành phố lớn với nhiều trung tâm tài chính và văn hóa.'),
        ('14', 'London', 'Anh', 'Thành phố nổi tiếng với lịch sử lâu đời và đa dạng văn hóa.'),
        ('15', 'Sydney', 'Úc', 'Thành phố ven biển nổi tiếng với nhà hát Opera và bãi biển Bondi.'),
        ('16', 'Seoul', 'Hàn Quốc', 'Thủ đô của Hàn Quốc với nền văn hóa K-pop nổi bật.'),
        ('17', 'Bangkok', 'Thái Lan', 'Thành phố nổi tiếng với đền chùa và ẩm thực đường phố.'),
        ('18', 'Singapore', 'Singapore', 'Quốc đảo nổi tiếng với sự phát triển và đa dạng văn hóa.'),
        ('19', 'Dubai', 'UAE', 'Thành phố sa mạc nổi tiếng với các công trình kiến trúc hiện đại.'),
        ('20', 'Barcelona', 'Tây Ban Nha', 'Thành phố nổi tiếng với kiến trúc của Antoni Gaudí.');