@startuml yuh
skinparam Linetype ortho

entity User {
    id: uuid
    citizen_id: string
    email: string
    password: string
    avatar: string
    firstName: string
    lastName: string
    phone: string
    gender: bit
    address: string
    dateOfBirth: datetime
}

entity Favorite {
    id: uuid
    user_id: uuid
    service_id: uuid
    service_type: ServiceType
}

enum ServiceType {
    flight
    stay
}

entity Flight {
    id: uuid
    name: string
    base_fare: number
    discount: number
    taxes: number
    service_fee: number
    total_price: number
    airline_id: uuid
    departure_airport_id: uuid
    arrival_airport_id: uuid
    status: string
    gate: string
    departure_time: timestamp
    arrival_time: timestamp
    timezoneL: string
    duration: interval
}

entity Amenity {
    id: uuid
    name: string
    icon: string
    is_feature: boolean
}

entity ServiceAmenity {
    id: uuid
    amenity_id: uuid
    service_id: uuid
}

entity Seat {
    id: uuid
    number: string
    seat_class: SeatClass
    flight_id: uuid
    is_available: boolean
}

enum SeatClass {
    economy
    first
    business
}

entity Airport {
    id: uuid
    code: string
    name: string
    location_id: uuid
}

entity Airline {
    id: uuid
    name: string
    image: string
    ratingsL: number
    review_count: number
}

entity Review {
    id: uuid
    service_id: uuid
    user_id: uuid
    ratings: number
    content: string
}

entity Policy {
    id: uuid
    airline_id: uuid
    content: string
}

entity FeatureImage {
    id: uuid
    service_id: uuid
    url: string
}

entity FlightBooking {
    id: uuid
    user_id: uuid
    status: string
    date: timestamp
    seat_id: uuid
    flight_id: uuid
}

entity Stay {
    id: uuid
    name: string
    address: string
    location_id: uuid
    ratings: number
    type: StayType
    star_rating: number
    overview: string
    latitude: string
    longitude: string
}

entity Advantage {
    id: uuid
    stay_id: uuid
    name: string
}

enum StayType {
    hotel 
    motel 
    resort 
}

entity Room {
    id: uuid
    name: string
    stay_id: uuid
    base_fare: number
    discount: number
    taxes: number
    service_fee: number
    total_price: number
    type: string
    is_available: boolean
}

entity RoomBooking {
    id: uuid
    user_id: uuid
    citizen_id: uuid
    status: string
    date: timestamp
    room_id: uuid
    check_in: timestamp
    checkout: timestamp
}

entity Location {
    id: uuid
    city: string
    country: string
    description: string
}

entity Payment {
    id: uuid
    booking_id: uuid
    status: string
    date: timestamp
    payment_method
}

Favorite }|-up-|| User

FlightBooking }|-left-|| User
FlightBooking ||--|| Flight
FlightBooking ||--|| Seat
FlightBooking ||--|| Payment

RoomBooking }|-right-|| User
RoomBooking ||-left-|| Room
RoomBooking ||--|| Payment

Favorite }|-up-|| Stay
Favorite }|--|| Flight
Review }|-up-|| Stay 
Review }|--|| Flight
ServiceAmenity }|-up-|| Stay 
ServiceAmenity }|--|| Flight
Amenity }|--|| ServiceAmenity

Advantage }|-up-|| Stay
FeatureImage }|-up-|| Stay 
FeatureImage }|--|| Flight

Room }|-left-|| Stay 

Flight }|--|| Airline
Flight }|-left-|| Airport
Policy }|--|| Airport

Airport }|--|| Location
Stay }|--|| Location


Seat }|--|| Flight

@enduml